#!/bin/bash

# Test Build Script with Revert Capability
# This script tracks all changes made by build_arch_linux.sh and provides
# a way to revert them after testing

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Snapshot directory
SNAPSHOT_DIR="$HOME/.linuxtrack_build_snapshot_$(date +%Y%m%d_%H%M%S)"
REVERT_SCRIPT="$SNAPSHOT_DIR/revert.sh"

# Function to create snapshot
create_snapshot() {
    print_status "Creating system snapshot..."
    mkdir -p "$SNAPSHOT_DIR"
    
    # Record installed packages
    print_status "Recording installed packages..."
    pacman -Q > "$SNAPSHOT_DIR/packages_before.txt" 2>/dev/null || true
    yay -Q > "$SNAPSHOT_DIR/aur_packages_before.txt" 2>/dev/null || true
    
    # Record user groups
    print_status "Recording user groups..."
    groups > "$SNAPSHOT_DIR/groups_before.txt" 2>/dev/null || true
    
    # Record installed files/directories
    print_status "Recording installed locations..."
    {
        echo "# Files/directories to check for removal:"
        echo "/opt/bin/ltr_gui"
        echo "/opt/lib/linuxtrack"
        echo "/opt/share/linuxtrack"
        echo "/opt/xplane-sdk"
        echo "/etc/profile.d/xplane-sdk.sh"
    } > "$SNAPSHOT_DIR/installed_locations.txt"
    
    # Create revert script
    cat > "$REVERT_SCRIPT" << 'REVERT_EOF'
#!/bin/bash
# Revert script generated by test_build_with_revert.sh
# Run this script to revert changes made by build_arch_linux.sh

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

SNAPSHOT_DIR="$(dirname "$0")"

if [ ! -f "$SNAPSHOT_DIR/packages_before.txt" ]; then
    print_error "Snapshot files not found. Cannot revert."
    exit 1
fi

print_status "Reverting changes..."

# Remove newly installed packages
if [ -f "$SNAPSHOT_DIR/packages_after.txt" ]; then
    print_status "Removing newly installed packages..."
    # Get list of new packages
    NEW_PACKAGES=$(comm -13 <(sort "$SNAPSHOT_DIR/packages_before.txt") <(sort "$SNAPSHOT_DIR/packages_after.txt") | awk '{print $1}' | grep -v "^$" || true)
    
    if [ -n "$NEW_PACKAGES" ]; then
        print_warning "The following packages were installed and will be removed:"
        echo "$NEW_PACKAGES"
        read -p "Continue with package removal? (y/N): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            sudo pacman -Rns $NEW_PACKAGES 2>/dev/null || print_warning "Some packages could not be removed (may be dependencies)"
        else
            print_warning "Skipping package removal"
        fi
    fi
fi

# Remove AUR packages
if [ -f "$SNAPSHOT_DIR/aur_packages_after.txt" ]; then
    print_status "Removing newly installed AUR packages..."
    if command -v yay >/dev/null 2>&1; then
        NEW_AUR=$(comm -13 <(sort "$SNAPSHOT_DIR/aur_packages_before.txt" 2>/dev/null || echo "") <(sort "$SNAPSHOT_DIR/aur_packages_after.txt") | awk '{print $1}' | grep -v "^$" || true)
        if [ -n "$NEW_AUR" ]; then
            print_warning "The following AUR packages were installed:"
            echo "$NEW_AUR"
            read -p "Remove AUR packages? (y/N): " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                yay -Rns $NEW_AUR 2>/dev/null || print_warning "Some AUR packages could not be removed"
            fi
        fi
    fi
fi

# Remove installed files
print_status "Removing installed files..."
if [ -d "/opt/bin" ] && [ -f "/opt/bin/ltr_gui" ]; then
    print_status "Removing /opt installation..."
    sudo rm -rf /opt/bin/ltr_gui /opt/lib/linuxtrack /opt/share/linuxtrack 2>/dev/null || true
fi

# Remove X-Plane SDK
if [ -d "/opt/xplane-sdk" ]; then
    print_status "Removing X-Plane SDK..."
    sudo rm -rf /opt/xplane-sdk
fi

# Remove X-Plane SDK environment file
if [ -f "/etc/profile.d/xplane-sdk.sh" ]; then
    print_status "Removing X-Plane SDK environment file..."
    sudo rm -f /etc/profile.d/xplane-sdk.sh
fi

# Note: User group changes cannot be automatically reverted
# User would need to manually remove themselves from groups if needed
print_warning "Note: User group changes (plugdev, input) were made but cannot be automatically reverted."
print_warning "If you need to remove yourself from these groups, run:"
print_warning "  sudo gpasswd -d $USER plugdev"
print_warning "  sudo gpasswd -d $USER input"

print_success "Revert completed!"
print_status "Snapshot directory: $SNAPSHOT_DIR"
print_status "You can review the changes by comparing the 'before' and 'after' files."
REVERT_EOF
    
    chmod +x "$REVERT_SCRIPT"
    print_success "Snapshot created at: $SNAPSHOT_DIR"
    echo "$SNAPSHOT_DIR" > "$HOME/.linuxtrack_latest_snapshot"
}

# Function to update snapshot after build
update_snapshot() {
    print_status "Updating snapshot with post-build state..."
    
    # Record packages after
    pacman -Q > "$SNAPSHOT_DIR/packages_after.txt" 2>/dev/null || true
    yay -Q > "$SNAPSHOT_DIR/aur_packages_after.txt" 2>/dev/null || true
    
    # Record groups after
    groups > "$SNAPSHOT_DIR/groups_after.txt" 2>/dev/null || true
    
    print_success "Snapshot updated"
}

# Function to show usage
show_usage() {
    echo "Test Build Script with Revert Capability"
    echo ""
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --test          Run the build script and create snapshot (default)"
    echo "  --revert        Revert changes from the last snapshot"
    echo "  --list-snapshots List all available snapshots"
    echo "  --help          Show this help message"
    echo ""
    echo "The script will:"
    echo "  1. Create a snapshot of your system state"
    echo "  2. Run the build script"
    echo "  3. Update the snapshot with post-build state"
    echo "  4. Provide a revert script to undo changes"
}

# Main function
main() {
    if [ "$1" = "--revert" ]; then
        if [ -f "$HOME/.linuxtrack_latest_snapshot" ]; then
            LATEST=$(cat "$HOME/.linuxtrack_latest_snapshot")
            if [ -f "$LATEST/revert.sh" ]; then
                print_status "Running revert script from: $LATEST"
                "$LATEST/revert.sh"
            else
                print_error "Revert script not found in: $LATEST"
                exit 1
            fi
        else
            print_error "No snapshot found. Cannot revert."
            exit 1
        fi
        exit 0
    elif [ "$1" = "--list-snapshots" ]; then
        print_status "Available snapshots:"
        ls -d "$HOME/.linuxtrack_build_snapshot_"* 2>/dev/null | while read snap; do
            echo "  $snap"
        done || print_warning "No snapshots found"
        exit 0
    elif [ "$1" = "--help" ]; then
        show_usage
        exit 0
    fi
    
    # Default: run test
    print_status "Starting test build with revert capability..."
    
    # Check if we're in the right directory
    if [ ! -f "scripts/build_arch_linux.sh" ]; then
        print_error "This script must be run from the LinuxTrack X-IR source directory"
        exit 1
    fi
    
    # Create snapshot
    create_snapshot
    
    # Run the build script
    print_status "Running build script..."
    print_warning "The build script will install packages and modify your system."
    print_warning "All changes will be tracked and can be reverted using:"
    print_warning "  $0 --revert"
    echo ""
    read -p "Continue with build? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_warning "Build cancelled"
        exit 0
    fi
    
    # Run build script
    if ./scripts/build_arch_linux.sh; then
        print_success "Build completed successfully"
    else
        print_error "Build failed"
        print_status "You can still revert changes using: $0 --revert"
        exit 1
    fi
    
    # Update snapshot
    update_snapshot
    
    print_success "Test build completed!"
    print_status "Snapshot location: $SNAPSHOT_DIR"
    print_status "To revert changes, run: $0 --revert"
}

# Run main function
main "$@"


