.TH LTR_SERVER1 1 "July 2024" "LinuxTrack" "User Commands"
.SH NAME
ltr_server1 \- LinuxTrack server component
.SH SYNOPSIS
.B ltr_server1
.SH DESCRIPTION
.B ltr_server1
is a server component of the LinuxTrack head tracking system.
It handles communication between the tracking components and applications.
.SH SEE ALSO
.BR ltr_gui (1),
.BR mickey (1)
.SH AUTHOR
LinuxTrack Development Team
