function(detect_mingw)
    find_program(MINGW32_GCC_EXECUTABLE i686-w64-mingw32-gcc)
    find_program(MINGW64_GCC_EXECUTABLE x86_64-w64-mingw32-gcc)
    find_program(MINGW32_GPP_EXECUTABLE i686-w64-mingw32-g++)
    find_program(MINGW64_GPP_EXECUTABLE x86_64-w64-mingw32-g++)
    find_program(MINGW32_WINDRES_EXECUTABLE i686-w64-mingw32-windres)
    find_program(MINGW64_WINDRES_EXECUTABLE x86_64-w64-mingw32-windres)

    set(MINGW_FOUND FALSE)
    if(MINGW32_GCC_EXECUTABLE AND MINGW64_GCC_EXECUTABLE
       AND MINGW32_GPP_EXECUTABLE AND MINGW64_GPP_EXECUTABLE
       AND MINGW32_WINDRES_EXECUTABLE AND MINGW64_WINDRES_EXECUTABLE)
        set(MINGW_FOUND TRUE)
    endif()

    set(MINGW_FOUND ${MINGW_FOUND} CACHE BOOL "MinGW-w64 toolchains found" FORCE)
    set(MINGW32_GCC_EXECUTABLE ${MINGW32_GCC_EXECUTABLE} CACHE FILEPATH "i686 MinGW GCC" FORCE)
    set(MINGW64_GCC_EXECUTABLE ${MINGW64_GCC_EXECUTABLE} CACHE FILEPATH "x86_64 MinGW GCC" FORCE)
    set(MINGW32_GPP_EXECUTABLE ${MINGW32_GPP_EXECUTABLE} CACHE FILEPATH "i686 MinGW G++" FORCE)
    set(MINGW64_GPP_EXECUTABLE ${MINGW64_GPP_EXECUTABLE} CACHE FILEPATH "x86_64 MinGW G++" FORCE)
    set(MINGW32_WINDRES_EXECUTABLE ${MINGW32_WINDRES_EXECUTABLE} CACHE FILEPATH "i686 MinGW windres" FORCE)
    set(MINGW64_WINDRES_EXECUTABLE ${MINGW64_WINDRES_EXECUTABLE} CACHE FILEPATH "x86_64 MinGW windres" FORCE)
endfunction()
